import type { ExerciseImage, ExerciseInput } from '../../shared/schemas.js';

type Seed = Omit<ExerciseInput, 'images' | 'videoUrl' | 'muscles' | 'steps' | 'variations'> &
  Partial<Pick<ExerciseInput, 'muscles' | 'steps' | 'variations'>>;

// Photos from free-exercise-db (public domain, https://github.com/yuhonas/free-exercise-db),
// served via jsDelivr. Every entry there has a start (0.jpg) and end (1.jpg) position photo.
const IMG_BASE = 'https://cdn.jsdelivr.net/gh/yuhonas/free-exercise-db@main/exercises';

function photos(id: string, label: string, variationKey = ''): ExerciseImage[] {
  const prefix = label ? `${label}: ` : '';
  return [
    { url: `${IMG_BASE}/${id}/0.jpg`, caption: `${prefix}start position`, variationKey },
    { url: `${IMG_BASE}/${id}/1.jpg`, caption: `${prefix}end position`, variationKey },
  ];
}

export const seedImages: Record<string, ExerciseImage[]> = {
  'Warm-up': [
    ...photos('Walking_Treadmill', 'Walk'),
    ...photos('Arm_Circles', 'Arm circles'),
    ...photos('Bodyweight_Squat', 'Bodyweight squats'),
  ],
  Squats: photos('Bodyweight_Squat', ''),
  'Push-ups': [
    ...photos('Pushups', 'Standard', 'standard'),
    ...photos('Incline_Push-Up', 'Hands on bench', 'incline'),
  ],
  'Pull-up practice': [
    ...photos('Band_Assisted_Pull-Up', 'Assisted', 'assisted'),
    ...photos('Pullups', 'Full pull-up (lower slowly)', 'negative'),
  ],
  'Dumbbell shoulder press': photos('Dumbbell_Shoulder_Press', ''),
  'Dumbbell side raise': photos('Side_Lateral_Raise', ''),
  'Dumbbell front raise': photos('Front_Dumbbell_Raise', ''),
  'Back push-up': [
    ...photos('Bench_Dips', 'Bench dips', 'bench-dips'),
    ...photos('Hyperextensions_Back_Extensions', 'Back extension', 'back-extension'),
  ],
  'Dumbbell side bend': photos('Dumbbell_Side_Bend', ''),
  'Lat pulldown': [
    ...photos('Wide-Grip_Lat_Pulldown', 'Wide overhand', 'wide-overhand'),
    ...photos('Close-Grip_Front_Lat_Pulldown', 'Shoulder-width overhand', 'shoulder-overhand'),
    ...photos('Underhand_Cable_Pulldowns', 'Underhand', 'underhand'),
    ...photos('V-Bar_Pulldown', 'Neutral V-handle', 'neutral-v'),
    ...photos('One_Arm_Lat_Pulldown', 'One arm', 'one-arm'),
  ],
  'Seated cable row': [
    ...photos('Seated_Cable_Rows', 'V-handle', 'v-handle'),
    ...photos('Cable_Rope_Rear-Delt_Rows', 'Rope', 'rope'),
  ],
  'Lying leg raises': photos('Flat_Bench_Lying_Leg_Raise', ''),
  Plank: photos('Plank', '')
    .slice(0, 1)
    .map((i) => ({ ...i, caption: 'Hold this position' })),
  Stretching: [
    ...photos('Quad_Stretch', 'Quads').slice(0, 1),
    ...photos('Hamstring_Stretch', 'Hamstrings').slice(0, 1),
    ...photos('Chest_And_Front_Of_Shoulder_Stretch', 'Chest & shoulders').slice(0, 1),
    ...photos('Shoulder_Stretch', 'Shoulders').slice(0, 1),
  ].map((i) => ({ ...i, caption: i.caption.replace(': start position', '') })),
  'Incline treadmill walk': photos('Walking_Treadmill', ''),
  'Treadmill run': photos('Running_Treadmill', ''),
  'Rowing machine': photos('Rowing_Stationary', ''),
  'Stationary bike': photos('Bicycling_Stationary', ''),
  Elliptical: photos('Elliptical_Trainer', ''),
  'Stair climber': photos('Stairmaster', ''),
  'Jump rope': photos('Rope_Jumping', ''),
  'Battle ropes': photos('Battling_Ropes', ''),
  'Kettlebell swing': photos('One-Arm_Kettlebell_Swings', ''),
  'Sled push': photos('Sled_Push', ''),
  'Mountain climbers': photos('Mountain_Climbers', ''),
  'Jump squats': photos('Freehand_Jump_Squat', ''),
  'Jumping jacks': photos('Star_Jump', ''),
  Skaters: photos('Skating', ''),
};

// Default library from the project plan (section 7). Names are the identity used to avoid duplicates.
export const seedExercises: Seed[] = [
  {
    name: 'Warm-up',
    category: 'cardio',
    equipment: 'bodyweight',
    measure: 'time',
    heavyRest: false,
    muscles: ['Full body'],
    steps: [
      'Walk or do light cardio for about 3 minutes.',
      'Arm circles: 10 forwards, 10 backwards.',
      'Bodyweight squats: 10 slow reps.',
    ],
  },
  {
    name: 'Squats',
    category: 'legs',
    equipment: 'bodyweight',
    measure: 'reps',
    heavyRest: true,
    muscles: ['Quads', 'Glutes', 'Hamstrings', 'Core'],
    steps: [
      'Stand with feet shoulder-width apart.',
      'Push your hips back and bend the knees, keeping the chest up.',
      'Lower until your thighs are about parallel to the floor.',
      'Push through your heels to stand back up.',
    ],
  },
  {
    name: 'Push-ups',
    category: 'push',
    equipment: 'bodyweight',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Chest', 'Triceps', 'Front shoulders', 'Core'],
    steps: [
      'Hands slightly wider than your shoulders.',
      'Keep a straight line from head to heels.',
      'Lower your chest to just above the floor, then push back up.',
    ],
    variations: [
      {
        key: 'standard',
        name: 'Standard',
        description: 'Hands and toes on the floor.',
        works: 'Chest, triceps',
      },
      {
        key: 'knees',
        name: 'On knees',
        description: 'Knees on the floor, body straight from knees to head.',
        works: 'Easier version, same muscles',
      },
      {
        key: 'incline',
        name: 'Hands on bench',
        description: 'Hands on a bench, feet on the floor.',
        works: 'Easier version, more lower chest',
      },
    ],
  },
  {
    name: 'Pull-up practice',
    category: 'pull',
    equipment: 'machine',
    measure: 'reps',
    heavyRest: true,
    muscles: ['Lats', 'Biceps', 'Upper back'],
    steps: [
      'Use the assisted pull-up machine, or jump to the top of the bar.',
      'If jumping: lower yourself slowly over 3-5 seconds.',
      'Keep shoulders down and away from your ears.',
    ],
    variations: [
      {
        key: 'assisted',
        name: 'Assisted machine',
        description: 'Knees on the pad; more counterweight = easier.',
        works: 'Lats, biceps',
      },
      {
        key: 'negative',
        name: 'Slow negatives',
        description: 'Jump up, then lower slowly over 3-5 seconds.',
        works: 'Builds strength for full pull-ups',
      },
    ],
  },
  {
    name: 'Dumbbell shoulder press',
    category: 'push',
    equipment: 'dumbbell',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Shoulders', 'Triceps'],
    steps: [
      'Sit or stand with dumbbells at shoulder height, palms forward.',
      'Press the dumbbells straight up without locking the elbows hard.',
      'Lower slowly back to shoulder height.',
    ],
  },
  {
    name: 'Dumbbell side raise',
    category: 'push',
    equipment: 'dumbbell',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Side shoulders'],
    steps: [
      'Hold dumbbells at your sides, elbows slightly bent.',
      'Raise your arms out to the sides up to shoulder height.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Dumbbell front raise',
    category: 'push',
    equipment: 'dumbbell',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Front shoulders'],
    steps: [
      'Hold dumbbells in front of your thighs.',
      'Raise your arms straight in front of you to shoulder height.',
      'Lower slowly.',
    ],
  },
  {
    name: 'Back push-up',
    category: 'push',
    equipment: 'bodyweight',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Triceps', 'Lower back'],
    steps: ['Pick the version your trainer showed you (see grips/variations).'],
    variations: [
      {
        key: 'bench-dips',
        name: 'Bench dips',
        description:
          'Hands on a bench behind you, bend the elbows to lower your hips, then push up.',
        works: 'Triceps, chest',
      },
      {
        key: 'back-extension',
        name: 'Back extension',
        description:
          'On the back extension bench, lower your upper body, then lift until your body is straight.',
        works: 'Lower back, glutes',
      },
    ],
  },
  {
    name: 'Dumbbell side bend',
    category: 'core',
    equipment: 'dumbbell',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Obliques'],
    steps: [
      'Stand holding one dumbbell at your side.',
      'Bend sideways at the waist towards the dumbbell, then come back up.',
      'Do all reps, then switch sides.',
    ],
  },
  {
    name: 'Lat pulldown',
    category: 'pull',
    equipment: 'machine',
    measure: 'reps',
    heavyRest: true,
    muscles: ['Lats', 'Biceps', 'Upper back'],
    steps: [
      'Set the weight with the pin and lock your thighs under the pad.',
      'Pull the bar to your upper chest, leading with the elbows.',
      'Return slowly. Never pull behind the neck.',
    ],
    variations: [
      {
        key: 'wide-overhand',
        name: 'Wide overhand',
        description: 'Hands wider than shoulders, palms facing away.',
        works: 'Outer lats, back width',
      },
      {
        key: 'shoulder-overhand',
        name: 'Shoulder-width overhand',
        description: 'Hands at shoulder width, palms facing away.',
        works: 'Lats, more biceps',
      },
      {
        key: 'underhand',
        name: 'Underhand',
        description: 'Hands at shoulder width, palms facing you.',
        works: 'Lower lats, biceps',
      },
      {
        key: 'neutral-v',
        name: 'Neutral V-handle',
        description: 'V-handle, palms facing each other.',
        works: 'Middle back, lats',
      },
      {
        key: 'one-arm',
        name: 'One arm at a time',
        description: 'Single handle, pull with one arm, then switch.',
        works: 'Each side evenly',
      },
    ],
  },
  {
    name: 'Seated cable row',
    category: 'pull',
    equipment: 'machine',
    measure: 'reps',
    heavyRest: true,
    muscles: ['Middle back', 'Lats', 'Biceps'],
    steps: [
      'Set the weight with the pin. Sit tall with feet on the platform.',
      'Pull the handle to your belly (wide bar: to your chest).',
      'Squeeze your shoulder blades together for 1 second.',
      'Return slowly, keeping your back straight.',
    ],
    variations: [
      {
        key: 'v-handle',
        name: 'V-handle',
        description: 'Close grip, palms facing each other. Pull to the belly.',
        works: 'Middle back, lats',
      },
      {
        key: 'wide-bar',
        name: 'Wide bar',
        description: 'Wide overhand grip. Pull to the chest.',
        works: 'Upper back, rear shoulders',
      },
      {
        key: 'underhand-bar',
        name: 'Underhand bar',
        description: 'Shoulder-width grip, palms up.',
        works: 'Lower lats, biceps',
      },
      {
        key: 'rope',
        name: 'Rope',
        description: 'Rope handle, pull the ends apart as you reach your belly.',
        works: 'Upper back, rear shoulders',
      },
      {
        key: 'one-arm',
        name: 'One arm at a time',
        description: 'Single handle, one arm, then switch.',
        works: 'Each side evenly',
      },
    ],
  },
  {
    name: 'Lying leg raises',
    category: 'core',
    equipment: 'bodyweight',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Lower abs', 'Hip flexors'],
    steps: [
      'Lie on your back, legs together, hands under your hips.',
      'Lift your legs to vertical.',
      'Lower slowly without touching the floor.',
    ],
  },
  {
    name: 'Plank',
    category: 'core',
    equipment: 'bodyweight',
    measure: 'time',
    heavyRest: false,
    muscles: ['Core', 'Shoulders'],
    steps: [
      'Forearms and toes on the floor.',
      'Keep a straight line from head to heels.',
      'Keep your stomach tight and breathe.',
    ],
  },
  {
    name: 'Stretching',
    category: 'mobility',
    equipment: 'bodyweight',
    measure: 'time',
    heavyRest: false,
    muscles: ['Full body'],
    steps: [
      'Hold each stretch for 20-30 seconds, no bouncing.',
      'Legs: quads, hamstrings, calves.',
      'Upper body: chest, shoulders, lats, triceps.',
    ],
  },
  {
    name: 'Incline treadmill walk',
    category: 'cardio',
    equipment: 'machine',
    measure: 'time',
    heavyRest: false,
    muscles: ['Glutes', 'Calves', 'Hamstrings', 'Heart & lungs'],
    steps: [
      'Set the incline high (10-15%) and speed to a brisk walk (4-5.5 km/h).',
      'Stand tall and do not hold the rails.',
      'Walk steadily for 20-30 minutes.',
    ],
  },
  {
    name: 'Treadmill run',
    category: 'cardio',
    equipment: 'machine',
    measure: 'time',
    heavyRest: false,
    muscles: ['Quads', 'Hamstrings', 'Calves', 'Heart & lungs'],
    steps: [
      'Warm up with 3-5 minutes of walking.',
      'Run at a pace where you can still say short sentences.',
      'For intervals: 30 s fast, 60-90 s easy, repeat 8-10 times.',
    ],
  },
  {
    name: 'Rowing machine',
    category: 'cardio',
    equipment: 'machine',
    measure: 'time',
    heavyRest: false,
    muscles: ['Back', 'Legs', 'Arms', 'Heart & lungs'],
    steps: [
      'Push with the legs first, then lean back slightly, then pull the handle to your lower ribs.',
      'Return in reverse: arms, body, then legs.',
      'Keep a steady rhythm of about 20-26 strokes per minute.',
    ],
  },
  {
    name: 'Stationary bike',
    category: 'cardio',
    equipment: 'machine',
    measure: 'time',
    heavyRest: false,
    muscles: ['Quads', 'Glutes', 'Calves', 'Heart & lungs'],
    steps: [
      'Set the seat so your knee is slightly bent at the bottom.',
      'Pedal at a steady effort for 20-40 minutes.',
      'For intervals: 20-30 s hard, 60 s easy.',
    ],
  },
  {
    name: 'Elliptical',
    category: 'cardio',
    equipment: 'machine',
    measure: 'time',
    heavyRest: false,
    muscles: ['Legs', 'Glutes', 'Arms', 'Heart & lungs'],
    steps: [
      'Stand tall and hold the moving handles.',
      'Push and pull with your arms as your legs move.',
      'Keep a steady effort for 20-30 minutes.',
    ],
  },
  {
    name: 'Stair climber',
    category: 'cardio',
    equipment: 'machine',
    measure: 'time',
    heavyRest: false,
    muscles: ['Glutes', 'Quads', 'Calves', 'Heart & lungs'],
    steps: [
      'Stand tall and step with your whole foot.',
      'Hold the rails lightly for balance only.',
      'Climb at a steady pace for 10-20 minutes.',
    ],
  },
  {
    name: 'Jump rope',
    category: 'cardio',
    equipment: 'other',
    measure: 'time',
    heavyRest: false,
    muscles: ['Calves', 'Shoulders', 'Heart & lungs'],
    steps: [
      'Hold the handles at hip height, elbows close to your body.',
      'Turn the rope with your wrists.',
      'Jump just high enough to clear the rope, landing softly on the balls of your feet.',
    ],
  },
  {
    name: 'Battle ropes',
    category: 'cardio',
    equipment: 'other',
    measure: 'time',
    heavyRest: false,
    muscles: ['Shoulders', 'Arms', 'Core', 'Heart & lungs'],
    steps: [
      'Stand with knees bent, holding one rope end in each hand.',
      'Make fast waves by moving your arms up and down.',
      'Work 20-30 s, rest 30-60 s.',
    ],
  },
  {
    name: 'Kettlebell swing',
    category: 'cardio',
    equipment: 'other',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Glutes', 'Hamstrings', 'Core', 'Heart & lungs'],
    steps: [
      'Stand with feet wider than hips, kettlebell in front of you.',
      'Hinge at the hips and hike the bell back between your legs.',
      'Snap your hips forward to swing it to chest height. Arms stay relaxed.',
    ],
  },
  {
    name: 'Sled push',
    category: 'cardio',
    equipment: 'other',
    measure: 'time',
    heavyRest: false,
    muscles: ['Quads', 'Glutes', 'Calves', 'Heart & lungs'],
    steps: [
      'Hold the poles with arms extended, body leaning forward.',
      'Drive with short, powerful steps.',
      'Push 15-25 m, rest, repeat.',
    ],
  },
  {
    name: 'Mountain climbers',
    category: 'cardio',
    equipment: 'bodyweight',
    measure: 'time',
    heavyRest: false,
    muscles: ['Core', 'Shoulders', 'Hip flexors', 'Heart & lungs'],
    steps: [
      'Start in a high plank.',
      'Drive one knee toward your chest, then switch legs quickly.',
      'Keep your hips low and back flat.',
    ],
  },
  {
    name: 'Jump squats',
    category: 'cardio',
    equipment: 'bodyweight',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Quads', 'Glutes', 'Calves'],
    steps: [
      'Squat down with your chest up.',
      'Jump up explosively.',
      'Land softly and go straight into the next squat.',
    ],
  },
  {
    name: 'Burpees',
    category: 'cardio',
    equipment: 'bodyweight',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Full body', 'Heart & lungs'],
    steps: [
      'From standing, squat and put your hands on the floor.',
      'Jump your feet back into a plank and do a push-up (optional).',
      'Jump your feet in and jump up with arms overhead.',
    ],
  },
  {
    name: 'High knees',
    category: 'cardio',
    equipment: 'bodyweight',
    measure: 'time',
    heavyRest: false,
    muscles: ['Hip flexors', 'Quads', 'Calves', 'Heart & lungs'],
    steps: [
      'Run in place.',
      'Drive your knees up to hip height.',
      'Pump your arms and stay on the balls of your feet.',
    ],
  },
  {
    name: 'Jumping jacks',
    category: 'cardio',
    equipment: 'bodyweight',
    measure: 'time',
    heavyRest: false,
    muscles: ['Full body', 'Heart & lungs'],
    steps: [
      'Stand with feet together, arms at your sides.',
      'Jump your feet out while raising your arms overhead.',
      'Jump back to the start and repeat at a steady pace.',
    ],
  },
  {
    name: 'Skaters',
    category: 'cardio',
    equipment: 'bodyweight',
    measure: 'reps',
    heavyRest: false,
    muscles: ['Glutes', 'Quads', 'Calves'],
    steps: [
      'Leap sideways onto one foot.',
      'Swing the other leg behind you and touch the floor lightly.',
      'Leap back to the other side. Step instead of jumping to make it easier.',
    ],
  },
];
